# Poisson Regression

Stub for Poisson regression content

```{r packages}
library("tidyverse"); theme_set(theme_bw())
library("ggResidpanel")
```

## Model

Let $Y_i\in\{0,1,2,\ldots\}$ be a count (typically over some amount of time
or some amount of space) with associated explanatory variables 
$X_{i,1}, \ldots, X_{i,p}$.

\vspace{0.1in} \pause

Then a Poisson regression model is 
\[
Y_i \ind Po(\lambda_i) 
\]
and
\[
\log(\lambda_i) 
= \beta_0+\beta_1 X_{i,1} + \beta_2 X_{i,2} + \cdots +\beta_p X_{i,p} 
\]

As a reminder, $E[Y_i] = Var[Y_i] = \lambda_i$ and thus the variance of the 
observations increases as the mean increases. 


## Interpretation

When all explanatory variables are zero, then 
\[ 
E[Y_i|X_{i,1}=0, \ldots,X_{i,p}=0] \pause = \lambda_i \pause = e^{\beta_0}
\]
\pause
thus $\beta_0$ determines the \alert{expected response when all explanatory
variables are zero}.

\vspace{0.1in} \pause

More generally, 
\[ 
E[Y_i|X_{i,1}=x_1, \ldots,X_{i,p}=x_p] 
\pause 
= e^{\beta_0+\beta_1x_1+\cdots+\beta_px_p}.
\]
\pause
If $X_{i,1}$  increases by one unit, we have 
\[ 
E[Y_i|X_{i,1}=x_1+1, \ldots,X_{i,p}=x_p] 
\pause 
= e^{\beta_0+\beta_1(x_1+1)+\cdots+\beta_px_p}
\pause
= e^{\beta_0+\beta_1x_1+\cdots+\beta_px_p}e^{\beta_1}
\]
\pause
Thus 
\[
\frac{E[Y_i|X_{i,1}=x_1+1, \ldots,X_{i,p}=x_p]}{E[Y_i|X_{i,1}=x_1\phantom{+1}, \ldots,X_{i,p}=x_p]} 
\pause 
= e^{\beta_1}.
\]
\pause
Thus $e^{\beta_p}$ is the *multiplicative effect on the mean response for
a one unit increase in the associated explanatory variable when holding all
other explanatory variables constant.*

## Assumptions

- Independent observations
- Expected response 

## Diagnostics




