project:
  type: book

book:
  title: "Sports Analytics"
  author: "Jarad Niemi"
  date: "2025-02-28"
  chapters:
    - index.qmd
    - 01-intro.qmd
    - 02-distributions.qmd
    - 03-regression.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo      
    include-in-header:
      - file: macros.html


execute:
  freeze: auto
  
