project:
  type: book

book:
  title: "Sports Analytics"
  author: "Jarad Niemi"
  date: "2025-02-28"
  chapters:
    - index.qmd
    - part: background.qmd
      chapters:
      - 01-intro.qmd
      - 02-distributions.qmd
      - 03-regression.qmd
      - 04-poisson-regression.qmd
      - 05-logistic-regression.qmd
    - part: head-to-head.qmd
      chapters:
      - 06-margin-of-victory.qmd
      - 07-win-loss.qmd
      - win-tie-loss.qmd
      - chapters/head-to-head/offense-defense-rating.qmd
      - chapters/head-to-head/player-contribution.qmd
    - part: chapters/free-for-all/free-for-all.qmd
      chapters:
      - chapters/free-for-all/time.qmd
      - chapters/free-for-all/rank.qmd
    - part: chapters/bracketology/bracketology.qmd
      chapters:
      - chapters/bracketology/expected-score.qmd
    - summary.qmd
    - references.qmd
    - 99-data.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo


execute:
  freeze: auto
  
